### ISSUE TITLE
version

### ISSUE THREAD

**Issue by mikeyo** [ich777/unraid-it87-driver#1]
Is the latest release here the same vers as available in UNRAID community apps?

**Comment by ich777** [comment]
I really don't understand what you mean with that...?
Can you please be a bit more precise what you mean exactly?
On what Unraid version are you, is anything not working?

**Comment by mikeyo** [comment]
> I really don't understand what you mean with that...? Can you please be a bit more precise what you mean exactly? On what Unraid version are you, is anything not working?

I am on 6.11.5 in UNRAID and I installed the it87 plugin (02/11/2022) via community apps plugin. Is your it87 driver in this repo newer and if so how do we install it?

![image](https://user-images.githubusercontent.com/11810828/219333526-868d8104-69bf-42e3-8173-655962ceb3f4.png)

**Comment by ich777** [comment]
This is the repository for the plugin that you install through the CA App.
No, there is no newer driver available.

Please don't get confused by the plugin version, the plugin will always update itself and the driver.

**Comment by mikeyo** [comment]
> This is the repository for the plugin that you install through the CA App. No, there is no newer driver available.
> 
> Please don't get confused by the plugin version, the plugin will always update itself and the driver.

thank you for clearing this up for me.
